import PDFDocument from "pdfkit";
import { TravelRecord } from "../types";
import { formatInr } from "../utils/profit";
import { formatDisplayDate } from "../utils/dates";

function dash(value?: string | null): string {
  return value && value.trim() ? value : "—";
}

export function generateInvoicePdf(record: TravelRecord): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const left = 48;
    const right = pageWidth - 48;
    const width = right - left;

    doc.rect(0, 0, pageWidth, 96).fill("#0f766e");
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(22).text("TRAVEL INVOICE", left, 36, {
      width,
      align: "center",
    });
    doc.font("Helvetica").fontSize(11).text("Travel Record Management", left, 64, {
      width,
      align: "center",
    });

    let y = 120;
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(12);
    doc.text(`Invoice No: ${record.invoiceNumber}`, left, y);
    doc.font("Helvetica").text(`Date: ${formatDisplayDate(record.createdAt.slice(0, 10))}`, left, y, {
      width,
      align: "right",
    });

    y += 28;
    drawSection(doc, left, y, width, "Customer");
    y += 28;
    doc.font("Helvetica").fontSize(11).fillColor("#334155");
    doc.text(`Name: ${dash(record.customerName)}`, left + 8, y);
    y += 18;
    doc.text(`Phone: ${dash(record.customerPhone)}`, left + 8, y);

    y += 32;
    drawSection(doc, left, y, width, "Travel Details");
    y += 28;
    doc.font("Helvetica").fontSize(11).fillColor("#334155");
    doc.text(`From: ${record.fromPlace}`, left + 8, y);
    doc.text(`To: ${record.toPlace}`, left + width / 2, y);
    y += 20;
    doc.font("Helvetica-Bold").fillColor("#0f172a").text("Departure", left + 8, y);
    doc.text("Arrival", left + width / 2, y);
    y += 18;
    doc.font("Helvetica").fillColor("#334155");
    doc.text(`Date: ${formatDisplayDate(record.fromDate)}`, left + 8, y);
    doc.text(`Date: ${formatDisplayDate(record.toDate)}`, left + width / 2, y);
    y += 18;
    doc.text(`Time: ${record.fromTime}`, left + 8, y);
    doc.text(`Time: ${record.toTime}`, left + width / 2, y);

    y += 28;
    doc.text(`Driver: ${dash(record.driverName)}`, left + 8, y);
    doc.text(`Vehicle: ${dash(record.vehicleNumber)}`, left + width / 2, y);

    y += 36;
    drawSection(doc, left, y, width, "Financial Details");
    y += 32;
    moneyRow(doc, left, y, width, "Total Amount", record.totalAmount, false);
    y += 22;
    moneyRow(doc, left, y, width, "Driver Amount", record.driverAmount, false);
    y += 22;
    moneyRow(doc, left, y, width, "Petrol Amount", record.petrolAmount, false);
    y += 16;
    doc.moveTo(left + 8, y).lineTo(right - 8, y).strokeColor("#cbd5e1").stroke();
    y += 14;
    moneyRow(doc, left, y, width, "Profit", record.profit, true);

    y += 40;
    drawSection(doc, left, y, width, "Notes");
    y += 28;
    doc.font("Helvetica").fontSize(11).fillColor("#334155");
    doc.text(dash(record.notes), left + 8, y, { width: width - 16 });

    doc.fontSize(8).fillColor("#64748b").text(
      "Generated by Travel Record Management. Amounts are in Indian Rupees.",
      left,
      doc.page.height - 40,
      { width, align: "center" }
    );

    doc.end();
  });
}

function drawSection(
  doc: PDFKit.PDFDocument,
  left: number,
  y: number,
  width: number,
  title: string
): void {
  doc.roundedRect(left, y, width, 22, 4).fill("#ecfdf5");
  doc.fillColor("#0f766e").font("Helvetica-Bold").fontSize(11).text(title, left + 8, y + 6);
}

function moneyRow(
  doc: PDFKit.PDFDocument,
  left: number,
  y: number,
  width: number,
  label: string,
  amount: number,
  emphasize: boolean
): void {
  doc.font(emphasize ? "Helvetica-Bold" : "Helvetica").fontSize(emphasize ? 13 : 11);
  doc.fillColor(emphasize ? "#0f766e" : "#334155");
  doc.text(label, left + 8, y);
  doc.text(formatInr(amount), left, y, { width: width - 8, align: "right" });
}
